/*
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * 
 */

using System;

namespace Problem2 {
    public class Program {
        static void Main(string[] args) {
            var result = SumFibonacciSequence(4000000);
            Console.WriteLine(result);
            Console.ReadLine();
        }

        public static bool IsEven(int number) {
            return number % 2 == 0;
        }

        public static int SumFibonacciSequence(int limit) {
            var s1 = 1;
            var s2 = 1;
            var s3 = 0;
            var total = 0;
            while (s3 < limit) {
                s1 = s2;
                s2 = s3;
                if (IsEven(s3))
                    total += s3;
                s3 = s1 + s2;
            }

            return total;
        }
    }
}
